# Generated by Django 3.2 on 2021-05-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='dictionary',
        ),
    ]
